# Generated by Django 5.1.3 on 2024-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_comentario_delete_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
