# Generated by Django 5.1.3 on 2024-11-23 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_libro_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='likes',
        ),
        migrations.AddField(
            model_name='libro',
            name='anio_publicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='libros', to='mi_app.autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='calificacion_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.CharField(default='eng', max_length=10),
        ),
        migrations.AddField(
            model_name='libro',
            name='reseñas_texto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='total_calificaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
