# Generated by Django 5.1.3 on 2024-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_remove_libro_autor_remove_libro_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='five_star_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='four_star_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='one_star_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='three_star_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='two_star_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
