# Generated by Django 5.1.3 on 2024-11-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_libro_five_star_ratings_libro_four_star_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='calificacion_promedio',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='five_star_ratings',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='four_star_ratings',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='one_star_ratings',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='reseñas_texto',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='three_star_ratings',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='total_calificaciones',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='two_star_ratings',
        ),
    ]
