# Generated by Django 5.1.3 on 2024-11-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_remove_libro_calificacion_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.CharField(default='Español', max_length=10),
        ),
    ]
